---
title: "Figure 4"
format: html
---

```{r}
library(ggplot2)
library(CensusHLA)
```


# Prep work

Pull information on state codes and names from a package-stored function


```{r}
(state_info <- query_state_codes())
```

```{r, fig.height = 8, fig.width = 8}
ca_4 <- summarize_tract_genotypic_frequencies_by_h3_hexagon(
  state_abbreviation = 'CA',
  query_allele = 'A*11:01',
  h3_resolution = 4
)
ca_4$p1
##ggsave("fig_4_ca_4.svg", ca_4$p, device = "svg")
```

```{r, fig.height = 8, fig.width = 8}
ms_4 <-
  summarize_tract_genotypic_frequencies_by_h3_hexagon(
    state_abbreviation = 'MS',
    query_allele = 'B*58:01',
    h3_resolution = 4
  )
ms_4$p1
##ggsave("fig_4_ms_4.svg", ms_4$p1, device = "svg")
```

```{r, fig.height = 8, fig.width = 8}
ms_5 <-
  summarize_tract_genotypic_frequencies_by_h3_hexagon(
    state_abbreviation = 'MS',
    query_allele = 'B*58:01',
    h3_resolution = 5
  )
ms_5$p1
##ggsave("fig_4_ms_5.svg", ms_5$p1, device = "svg")
```


```{r, fig.height = 8, fig.width = 8}

tx_4 <-
  summarize_tract_genotypic_frequencies_by_h3_hexagon(
    state_abbreviation = 'TX',
    query_allele = 'A*11:01',
    h3_resolution = 4
  )
tx_4$p1
##ggsave("fig_4_tx_4.svg", tx_4$p1, device = "svg")
```

# System and Session info

```{r}

sessionInfo()
Sys.info()
```


