---
title: "Table 1 - US Census Corrections Country wide"
format: html
---
  
```{r}
library(CensusHLA)
```

```{r}
nmdp_hla_frequencies_by_race |> dplyr::filter(allele == 'A*11:01') |> 
  dplyr::filter(nmdp_race_code %in% c("AFA","API","CAU","HIS","NAM"))

tbl_out <-  nmdp_hla_frequencies_by_race |> dplyr::filter(allele == 'A*11:01') |> 
  dplyr::filter(nmdp_race_code %in% c("AFA","API","CAU","HIS","NAM"))
#write.csv(tbl_out, "tbl1_a11_nmdp_frequencies.csv")
```



```{r}
#| label: US Census percetnage table
#| echo: false
#| code-fold: true
#| warning: false
#| message: false
#| execute: true
#| output: true
us_pop_multirace_adjusted_in_nmdp_codes
# Export as a csv
#write.csv(us_pop_multirace_adjusted_in_nmdp_codes, "tbl1_us_pop_multirace_adjusted_in_nmdp_codes.csv")
```


```{r}
nmdp_hla_frequencies_by_race_us_2020_census_adjusted |> 
  dplyr::filter(allele == 'A*11:01') |> 
  dplyr::select(allele,nmdp_race_code,us_2020_percent_pop,nmdp_calc_gf,us_2020_nmdp_gf) |> 
  dplyr::arrange(desc(us_2020_percent_pop)) #|> 


tbl_out <- 
  nmdp_hla_frequencies_by_race_us_2020_census_adjusted |> 
  dplyr::filter(allele == 'A*11:01') |> 
  dplyr::select(allele,nmdp_race_code,us_2020_percent_pop,nmdp_calc_gf,us_2020_nmdp_gf) |> 
  dplyr::arrange(desc(us_2020_percent_pop))  
#write.csv(tbl_out,"tbl1_nmdp_us_adjusted_frequencies.csv")
```


# System and Session Information

```{r}
sessionInfo()
Sys.info()
```

