```{r}
library(ggplot2)
library(CensusHLA)
```


```{r}
state_frequencies <- census_adjusted_nmdp_hla_frequencies_by_state |> dplyr::filter(allele == 'A*11:01')

out_data <- state_frequencies |>
  dplyr::ungroup() |>
  dplyr::group_by(region, census_region, fips) |>
  dplyr::summarize(gf = sum(us_2020_nmdp_gf))

gg_state <- usmap::plot_usmap(
  data = out_data,
  regions = "states",
  #exclude = c('Alaksa','Hawaii'),
  exclude = c('AK', 'HI'),
  values = "gf",
  color = "black",
  linewidth = 0.1
) +
  viridis::scale_fill_viridis(option = "plasma", direction = 1)
gg_state
## use ggsave to save an svg object of gg_stae
#ggsave("fig_1_state_map.svg", gg_state, device = "svg")
   
```

```{r}

ak <-
  census_adjusted_nmdp_hla_frequencies_by_county |> dplyr::filter(state == 'Alaska' &
                                                                               allele == 'A*11:01')
hi <-
  census_adjusted_nmdp_hla_frequencies_by_county |> dplyr::filter(state == 'Hawaii' &
                                                                               allele == 'A*11:01')

state_county_frequencies <- rbind(ak, hi)

out_data <- state_county_frequencies |>
  dplyr::ungroup() |>
  dplyr::filter(allele == 'A*11:01') |>
  dplyr::group_by(region, state, census_region, county, fips, loci, allele) |>
  dplyr::summarize(us_2020_nmdp_gf_sum = sum(us_2020_nmdp_gf)) |>
  dplyr::filter(!(is.na(us_2020_nmdp_gf_sum))) |>
  # Create a STATEFP and COUNTYFP column by breaking the fips column on the 3rd character to the end
  dplyr::mutate(STATEFP = substr(fips, 1, 2),
                COUNTYFP = substr(fips, 3, nchar(fips)))

gg_ak_and_hi <- usmap::plot_usmap(
  data = out_data,
  regions = "counties",
  #exclude = c('Alaksa','Hawaii'),
  include = c('AK', 'HI'),
  values = "us_2020_nmdp_gf_sum",
  color = "black",
  linewidth = 0.1
) +
  viridis::scale_fill_viridis(option = "plasma", direction = 1)
gg_ak_and_hi
#ggsave("fig_1_ak_and_hi_map.svg", gg_ak_and_hi, device = "svg")
```

# System and Session info

```{r}

sessionInfo()
Sys.info()
```


