---
title: "Test Roy 2025 Figures and tables"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
format:
  html:
    toc: true
    toc_depth: 4
    toc_float: yes
    toc-location: left
    code-fold: true
    code-tools: true
    source: true
    toggle: false
    errors: false
    warnings: false
    message: false
    caption: none
    df_print: paged
    toctitle: "Contents"
    theme: cosmo
    embed-resources: true
---

```{r setup, include=FALSE}
library(CensusHLA)
library(ggplot2)
library(dplyr)
```

# Introduction

+ Once you've downloaded all the requisite source information her the package's instructions, you can build the package and re-create Figures and Tables published in Roy2025
+ This vignette is provided to enable anyone to see the source data and methodology behind our publication.

# Figure 1

## 1A - Continental US A11 

```{r a11 by state prep}
state_frequencies <- CensusHLA::census_adjusted_nmdp_hla_frequencies_by_state |> dplyr::filter(allele == 'A*11:01')

out_data <- state_frequencies |>
  dplyr::ungroup() |>
  dplyr::group_by(region, census_region, fips) |>
  dplyr::summarize(gf = sum(us_2020_nmdp_gf))

gg_state <- usmap::plot_usmap(
  data = out_data,
  regions = "states",
  #exclude = c('Alaksa','Hawaii'),
  exclude = c('AK', 'HI'),
  values = "gf",
  color = "black",
  linewidth = 0.1
) +
  viridis::scale_fill_viridis(option = "plasma", direction = 1)
```


```{r a11_by_state_plot}
gg_state
```

```{r a11 by state table}
out_data |> 
  dplyr::mutate(gf = round(gf,4)) |> 
  dplyr::rename(
    `State` = region,
    `Census Region` = census_region,
    `FIPS` = fips,
    `Population-Adjusted Genotypic Frequency` = gf
  ) |>
  DT::datatable(
    ,filter = 'top'
    ,rownames = FALSE
    ,extensions = 'Buttons', options = list(
      scrollX=TRUE,
      pageLength = 10,
      dom = 'Bfrtip',
      buttons = c('csv', 'excel')
      )
    )
```


# References

::: {#refs}
